### ISSUE TITLE
Unwanted characters are inserted when escaping CSS strings

### ISSUE THREAD

**Issue by nibushibu** [riot/compiler#121]
I hope you can check my repository below.
https://github.com/nibushibu/Getup

After compilation, unnecessary characters are inserted into CSS (SCSS) described in the file `/ src/riot/my-app.riot`.

Before
```css
/* style tag (scss) in `my-app.riot` */

h1 {
  color: green;
  display: flex;
}

.unmount-animation {
  opacity: 1;
  transition: opacity 1s;

  &.is-unmount {
    opacity: 0;
  }
}
```

After (compiled)
```css
my-app h1,[is="my-app"] h1{A   color: green;A   display: flex; } my-app AA.unmount-animation,[is="my-app"] AA.unmount-animation{A   opacity: 1;A   transition: opacity 1s; } my-app A   .unmount-animation.is-unmount,[is="my-app"] A   .unmount-animation.is-unmount{A     opacity: 0; }A
```

When I checked why the unwanted `A` character was inserted, I found that it was inserted after` cssEscape () `was executed.

https://github.com/riot/compiler/blob/227c544356241878383ae2101d9ec593524c417c/src/generators/css/index.js#L105-L108

`cssEscape (preprocessorOutput.code)`

By rewriting the above part (2 places) as below, we could avoid the problem for the time being.

`preprocessorOutput.code`

I think the above is temporary workaround, but I could not find a fundamental solution.

If this is a problem with my file, please point out the cause, or if it is a bug, please help me solve it. 🙇
